pipeline {
    agent any 
    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out code'
                cleanWs()
                checkout scm
            }
        }    
        stage('Code Build') {
            steps {
                echo 'Building the code with maven'
                sh 'cd maven-testing && mvn -B -DskipTests clean package'
            }
        }
        stage('Docker Build') {
            steps {
               echo "Building docker image"
               sh 'docker build -t ssksanthosh/maven-testing .'
            }
        }
    }
}
